// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `service`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`

/// Ajoute un compte et tente de l'enregistrer immédiatement.
///
/// # Erreurs
///
/// Renvoie un message lisible si les paramètres sont invalides ou si le compte
/// existe déjà. Un échec d'enregistrement n'est **pas** une erreur : il est
/// consigné dans le champ `status` du compte renvoyé.
Future<AccountView> addAccount({
  required String label,
  required String username,
  required String password,
  required String server,
  required String transport,
}) => OpendialBridge.instance.api.crateApiAccountsAddAccount(
  label: label,
  username: username,
  password: password,
  server: server,
  transport: transport,
);

/// Renvoie la liste des comptes configurés.
Future<List<AccountView>> listAccounts() =>
    OpendialBridge.instance.api.crateApiAccountsListAccounts();

/// Relance l'enregistrement d'un compte existant.
Future<AccountView> registerAccount({required String accountId}) =>
    OpendialBridge.instance.api.crateApiAccountsRegisterAccount(
      accountId: accountId,
    );

/// Retire un compte et le désenregistre.
Future<void> removeAccount({required String accountId}) => OpendialBridge
    .instance
    .api
    .crateApiAccountsRemoveAccount(accountId: accountId);

/// Compte tel que l'interface le reçoit.
///
/// Les champs sont en camelCase à dessein : `flutter_rust_bridge` les
/// transpose tels quels côté Dart, où c'est la convention. Les renommer en
/// snake_case obligerait l'interface à jongler entre deux styles.
class AccountView {
  /// Identifiant stable.
  final String id;

  /// Libellé affiché.
  final String label;

  /// Adresse d'enregistrement.
  final String addressOfRecord;

  /// Hôte du serveur.
  final String registrarHost;

  /// Port du serveur, ou 0 si le défaut du transport s'applique.
  final int registrarPort;

  /// Transport : `"udp"`, `"tcp"` ou `"tls"`.
  final String transport;

  /// État : `"unregistered"`, `"registering"`, `"registered"` ou `"failed"`.
  final String status;

  /// Détail lisible, vide si rien à signaler.
  final String statusDetail;

  const AccountView({
    required this.id,
    required this.label,
    required this.addressOfRecord,
    required this.registrarHost,
    required this.registrarPort,
    required this.transport,
    required this.status,
    required this.statusDetail,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      addressOfRecord.hashCode ^
      registrarHost.hashCode ^
      registrarPort.hashCode ^
      transport.hashCode ^
      status.hashCode ^
      statusDetail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          addressOfRecord == other.addressOfRecord &&
          registrarHost == other.registrarHost &&
          registrarPort == other.registrarPort &&
          transport == other.transport &&
          status == other.status &&
          statusDetail == other.statusDetail;
}

/// Erreur franchissant la frontière FFI sous forme sérialisable.
///
/// `flutter_rust_bridge` ne peut pas transporter l'erreur du domaine telle
/// quelle : on la réduit à un message, que Dart affiche directement.
///
/// Le type généré côté Dart n'implémente pas `toString()` : interpoler
/// l'objet afficherait `Instance of 'FfiErrorInfo'` à l'utilisateur. Il faut
/// donc **toujours lire `.message`** dans l'interface — c'est la raison pour
/// laquelle le champ est public et unique.
class FfiErrorInfo implements FrbException {
  /// Message prêt à être affiché.
  final String message;

  const FfiErrorInfo({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiErrorInfo &&
          runtimeType == other.runtimeType &&
          message == other.message;
}
