// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `describe_call_state_machine`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Version d'opendial, telle que déclarée dans le crate du domaine.
///
/// Le premier appel de l'interface au démarrage : si cette valeur s'affiche,
/// tout le pont fonctionne.
String version() => OpendialBridge.instance.api.crateApiSystemVersion();

/// Exécute une série de vérifications et renvoie leurs résultats.
///
/// Chaque ligne indique une capacité observée depuis Rust. Utilisé par l'écran
/// de diagnostic de l'interface, et utile pour vérifier une machine avant de
/// signaler un bug.
Future<List<DiagnosticLine>> runDiagnostics() =>
    OpendialBridge.instance.api.crateApiSystemRunDiagnostics();

/// Décrit les états d'enregistrement connus du domaine.
///
/// Permet à l'interface de valider qu'elle interprète correctement les chaînes
/// de statut qu'elle recevra du domaine.
Future<List<String>> describeRegistrationStates() =>
    OpendialBridge.instance.api.crateApiSystemDescribeRegistrationStates();

/// Ajoute deux nombres.
///
/// Fonction volontairement triviale, conservée comme test de fumée minimal :
/// si `add` échoue alors que `version` réussit, le problème vient de la
/// génération des bindings, pas du chargement de la bibliothèque.
int add({required int a, required int b}) =>
    OpendialBridge.instance.api.crateApiSystemAdd(a: a, b: b);

/// Description d'une ligne affichée dans l'interface de diagnostic.
class DiagnosticLine {
  /// Intitulé du test.
  final String label;

  /// Valeur observée.
  final String value;

  /// Le test a-t-il réussi ?
  final bool ok;

  const DiagnosticLine({
    required this.label,
    required this.value,
    required this.ok,
  });

  @override
  int get hashCode => label.hashCode ^ value.hashCode ^ ok.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosticLine &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          value == other.value &&
          ok == other.ok;
}
